---
name: "TVHeadend"
guid: "3fd018e5-5e78-4e58-b280-a0c068febee0"
version: "5.0.0.0"
jellyfin_version: "10.5.0.0"
owner: "jellyfin"
overview: "Manage TVHeadend from Jellyfin"
description: "Manage TVHeadend from Jellyfin"
category: "LiveTV"
artifacts:
- "TVHeadEnd.dll"
changelog: >
  changelog
